# Generated by Django 4.0.4 on 2022-04-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=60)),
                ('img', models.CharField(max_length=500)),
                ('audio_link', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
